# Ranges:
obstacle_range: 2.5
raytrace_range: 3.0

# Robot:
footprint: [[-0.05, 0.1], [0.16, 0.1], [0.16, -0.1], [-0.05, -0.1]]
robot_radius: 0.20

# Map:
inflation_radius: 0.10

transform_tolerance: 1.0

# Sensors:
# observation_sources: laser_scan_sensor point_cloud_sensor
# laser_scan_sensor: {sensor_frame: frame_name, data_type: LaserScan, topic: topic_name, marking: true, clearing: true}
# point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}