robot:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    position:
      YOUR_ROBOT_JOINT:
        type: effort_controllers/JointPositionController
        joint: YOUR_ROBOT_JOINT
        pid: { p: 10.0, i: 0.0, d: 1.0 }
      YOUR_OTHER_ROBOT_JOINT:
        type: effort_controllers/JointPositionController
        joint: YOUR_ROBOT_JOINT
        pid: { p: 5.0, i: 2.0, d: 1.0 }
